apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: silver-octo-couscous
  name: silver-octo-couscous-app
spec:
  project: silver-octo-couscous-project
  source:
    repoURL: https://github.com/alagroy-42/silver-octo-couscous
    targetRevision: master
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

