Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_url = "https://app.vagrantup.com/centos/boxes/7"

# CONFIGURATION SERVER VM
    config.vm.define "cristinaS" do |control|
        control.vm.hostname = "cristinaS"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.network "forwarded_port", guest: 6443, host: 6443
        control.vm.provider "virtualbox" do |v|
            v.cpus = 1
            v.memory = 512
            v.customize ["modifyvm", :id, "--name", "cristinaS"]
        end
        control.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
        control.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
        control.vm.provision "shell", privileged: true, path: "k3s.sh"
    end

# CONFIGURATION SERVER WORKER MV
    config.vm.define "cristinaSW" do |control|
        control.vm.hostname = "cristinaSW"
        control.vm.network "private_network", ip: "192.168.42.111"
        control.vm.provider "virtualbox" do |v|
            v.cpus = 1
            v.memory = 512
            v.customize ["modifyvm", :id, "--name", "cristinaSW"]
        end
        control.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
        control.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
        control.vm.provision "shell", privileged: true, path: "k3sworker.sh"
    end

end
