### IMPORTING CONFIGURATION VARIABLES ###
require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
configs     = YAML.load_file("#{current_dir}/config.yml")
vm          = configs['config']['vm']
server      = configs['config']['server']
worker      = configs['config']['worker']
user        = configs['config']['user']

### VAGRANT CONFIGURATION ###
Vagrant.configure(2) do |config|
    config.vm.box = "centos/8"
    config.vm.box_url = "https://app.vagrantup.com/centos/boxes/8"

# CONFIGURATION SERVER VM
    config.vm.define server['name'] do |control|
        control.vm.hostname = server['name']
        control.vm.network "private_network", ip: server['ip']
        control.vm.provider "virtualbox" do |v|
            v.cpus = vm['cpus']
            v.memory = vm['memory']
            v.customize ["modifyvm", :id, "--name", server['name']]
        end
        control.vm.provision "file", source: user['ssh_key_private'], destination: vm['ssh_key_private']
        control.vm.provision "file", source: user['ssh_key_public'], destination: vm['ssh_key_public']
        control.vm.provision "shell", path: server['script'], args: [
            vm['ssh_key_private'],
            server['token_file'],
            user['name'],
            user['ip'],
            user['token_file']
        ]
    end

# CONFIGURATION SERVER WORKER MV
    config.vm.define worker['name'] do |control|
        control.vm.hostname = worker['name']
        control.vm.network "private_network", ip: worker['ip']
        control.vm.provider "virtualbox" do |v|
            v.cpus = vm['cpus']
            v.memory = vm['memory']
            v.customize ["modifyvm", :id, "--name", worker['name']]
        end
        control.vm.provision "file", source: user['ssh_key_private'], destination: vm['ssh_key_private']
        control.vm.provision "file", source: user['ssh_key_public'], destination: vm['ssh_key_public']
        control.vm.provision "shell", path: worker['script'], args: [
            vm['ssh_key_private'],
            user['name'],
            user['ip'],
            user['token_file'],
            server['ip']
        ]
    end

end
