Vagrant.configure(2) do |config|
    # [...]
    config.vm.box = "centos/8"
    config.vm.box_url = "https://app.vagrantup.com/centos/boxes/8"

# CONFIGURATION SERVER VM
    config.vm.define "cristinaS" do |control|
        control.vm.hostname = "cristinaS"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provider "virtualbox" do |v|
            v.cpus = 1
            v.memory = 512
            v.customize ["modifyvm", :id, "--name", "cristinaS"]
            # [...]
        end
        config.vm.provision :shell, :inline => SHELL
            # [...]
        SHELL
        control.vm.provision "shell", path: REDACTED
        # control.vm.provision "file", source: "./.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
        # control.vm.provision "file", source: "./.ssh/id_rsa", destination: "/tmp/id_rsa"
    end

# CONFIGURATION SERVER WORKER MV
    config.vm.define "cristinaSW" do |control|
        control.vm.hostname = "cristinaSW"
        control.vm.network "private_network", ip: "192.168.42.111"
        control.vm.provider "virtualbox" do |v|
            v.cpus = 1
            v.memory = 512
            v.customize ["modifyvm", :id, "--name", "cristinaSW"]
            # [...]
        end
        config.vm.provision "shell", inline: <<-SHELL
            # [..]
        SHELL
        control.vm.provision "shell", path: REDACTED
        # control.vm.provision "file", source: "./.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
        # control.vm.provision "file", source: "./.ssh/id_rsa", destination: "/tmp/id_rsa"
    end

end
